# XRTK Azure Pipelines build configuration

resources:
  repositories:
    - repository: pipeline_repo
      type: github
      name: XRTK/AzurePipelines
      endpoint: XRTK

variables:
  project.name: 'XRTK.WindowsMixedReality'
  project.upmSha: ''
  package.name: 'com.xrtk.wmr'
  package.version: ''
  EditorPath: ''
  LogDirectory: ''
  ${{ if eq( variables['build.reason'], 'PullRequest' ) }}:
    date: ''
  ${{ if ne( variables['build.reason'], 'PullRequest' ) }}:
    date: ${{ '$(Date:yyyyMMdd)' }}
  isReleaseBuild: $[ and( eq(variables['Build.SourceBranchName'], 'master'), or( eq(variables['build.reason'], 'BatchedCI'), eq(variables['build.reason'], 'Manual') ) ) ]
  isPreviewBuild: $[ and( eq(variables['System.PullRequest.TargetBranch'], 'master'), eq(variables['build.reason'], 'PullRequest') ) ]

name: $(package.name) ${{ coalesce( variables['date'], '$(System.PullRequest.PullRequestNumber)', '$(Date:yyyyMMdd)' ) }}$(Rev:.r)

pr:
  autoCancel: true
  branches:
   include:
     - master
     - development
     - feature/*
  paths:
    include:
    - azure-pipelines.yml
    - azure_pipelines/*
    - XRTK.WindowsMixedReality/*
    - Submodules/*
    exclude:
      - '*'
      - XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/README.md
      - XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/LICENSE.md
      - XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/.github/*

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - azure-pipelines.yml
      - azure_pipelines/*
      - XRTK.WindowsMixedReality/*
      - Submodules/*
    exclude:
      - '*'
      - XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/README.md
      - XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/LICENSE.md
      - XRTK.WindowsMixedReality/Packages/com.xrtk.wmr/.github/*

extends:
  template: common.yml@pipeline_repo
  parameters:
    # Unity -buildTarget command line args https://docs.unity3d.com/Manual/CommandLineArguments.html
    # Standalone, Win, Win64, OSXUniversal, Linux64, iOS, Android, WebGL, XboxOne, PS4, WindowsStoreApps, Switch, tvOS, Lumin
    # TODO: Only use XRTK defined platform targets for build
    targets:
      - Win64
      - WindowsStoreApps
